config/routes.rb
Rails.application.routes.draw do
  root to: "home#home"
  get "skills", to: "home#skills"
  get "about", to: "home#about"
  get "download_cv", to: "home#download_cv"
  get "projects", to: "home#projects"
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/historico_profissional.rb
class HistoricoProfissional < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def skills
  end

  def about
    @historico_profissional = HistoricoProfissional.order(created_at: :desc)
  end

  def download_cv
    send_file("#{Rails.root}/public/pdfs/curriculo.pdf")
  end

  def protectes
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1 class="title-about">Sobre mim. Carreira.</h1>
<div class="row infos">
  <div class="col-lg-6" style="text-align: right">
    <%= image_tag('/images/perfil.jpeg', size: "400x400", class: "perfil")%>  
  </div>
  <div class="col-lg-5 about">
    Olá, me chamo Luiz Davi 😆 <br>
    Sou estudante da UFAPE (Universidade Federal do Agreste de Pernambuco), 
    Bacharelando em <strong>Ciências da computação</strong>! Atuo como 
    desenvolvedor de Software desde 2022.<br><br>
    
    Sou empenhado no meu trabalho e busco sempre aprender um pouquinho todo dia, 
    apaixonado por tecnologia. Estou iniciando minha carreira e buscando inspiração 
    nos desafios, são sempre o melhor caminho para o sucesso.
    Tenho um pé no Back-End, mas as vezes dou uma escapadinha para o front 😅, sempre 
    bom aprender de tudo um pouco.<br><br>
    <div style="text-align: right">
      <a type="button" class="btn btn-outline-secondary" href=<%= download_cv_path %> style="border: none; color: white; padding: 20px">
        <%= image_tag('/images/download.png', size: "20x20") %> Baixe meu CV 😉
      </a>
    </div>
  </div>
</div>
<br><br>
<h2 class="historic-title">Histórico Profissional</h2>
<% @historico_profissional.each do |hp| %>
  <div class="historic">
    <h5><%= hp.funcao %>_<%= hp.regime %></h5>
    <%= hp.empresa %> <label style="color: grey">• <%= hp.cidade %>, <%= hp.estado %></label><br>
    <div style="color: grey"><%= hp.inicio %>_<%= hp.fim %></div>
  </div>
  <br>
<% end %>

app/views/home/home.html.erb
<h1 class="home" >Luiz Davi M. de Matos</h1>
<label>Engenheiro de Software</label>

app/views/home/projects.html.erb
<div class="projects">
  <h1 class="title-projects">Trabalhos. Estudos.</h1>
  <h1 class="title-projects">Hobbies.</h1>
  <div class="row">
    <div class="col-md-auto">
      <div class=" card-project">
        <strong>To-do List</strong><br>
        Sistema para lista de afazeres.<br><br>
        <a type="button" target="_blank" href="https://to-do-list-v360-project.herokuapp.com/users/sign_in" class="demo">Demo</a>
        <a type="button" target="_blank" href="https://github.com/luiz-davi/todo_list" class="demo">Code</a>
      </div>
    </div>
    <div class="col-md-auto">
      <div class=" card-project">
        <strong>MyPage</strong><br>
        Meu cv online.<br><br>
        <a type="button" target="_blank" href="https://luiz-davi.herokuapp.com/" class="demo">Demo</a>
        <a type="button" target="_blank" href="https://github.com/luiz-davi/my-page" class="demo">Code</a>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-auto">
      <div class=" card-project">
        <strong>Pizza Delivery</strong><br>
        Gerenciamento de pedidos de pizza.<br><br>
        <a type="button" target="_blank" href="https://deliverypizza-es.herokuapp.com/" class="demo">Demo</a>
        <a type="button" target="_blank" href="https://github.com/esDeliveryOrganization/pizza-Delivery-system" class="demo">Code</a>
      </div>
    </div>
    <div class="col-md-auto">
      <div class=" card-project">
        <strong>Programas Acadêmicos</strong><br>
        Projeto destinado ao Gerenciamento de programas universitarios.<br><br>
        <a type="button" target="_blank" href="https://tjdv-programas-academicos.herokuapp.com/" class="demo">Demo</a>
        <a type="button" target="_blank" href="https://github.com/Projeto-Des-SW/tjdv_programas_academicos" class="demo">Code</a>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-auto">
      <div class=" card-project">
        <strong>FlashChat</strong><br>
        App para troca de mensagens.<br><br>
        <a type="button" target="_blank" href="https://github.com/luiz-davi/flash-chat-flutter" class="demo">Code</a>
      </div>
    </div>
    <div class="col-md-auto">
      <div class=" card-project">
        <strong>BitCoin Ticker</strong><br>
        App para converter moedas.<br><br>
        <a type="button" target="_blank" href="https://github.com/luiz-davi/bitcoin-ticker-flutter" class="demo">Code</a>
      </div>
    </div>
  </div>
</div>

app/views/home/skills.html.erb
<div class=" infos">
  <h1 class="title">Habilidades.</h1><br>
  <div class="row">
    <div class="col-lg-4">
      <div class="row">
        <div class="col-md-4 col-lg-4 icons" onmouseover="showRails()" onmouseout="hideRails()">
          <%= image_tag '/images/rails.svg', width: 64%>
        </div>
        <div class="col-md-4 col-lg-4 icons" onmouseover="showGraphql()" onmouseout="hideGraphql()">
          <%= image_tag '/images/graphql.svg', width: 64%>
        </div>
        <div class="col-md-4 col-lg-4 icons"  onmouseover="showHeroku()" onmouseout="hideHeroku()">
          <%= image_tag '/images/heroku.svg', width: 64%>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-4 col-lg-4 icons" onmouseover="showRuby()" onmouseout="hideRuby()">
          <%= image_tag '/images/ruby.svg', width: 64%>
        </div>
        <div class="col-md-4 col-lg-4 icons" onmouseover="showPostgresql()" onmouseout="hidePostgresql()">
          <%= image_tag '/images/postgresql.svg', width: 64%>
        </div>
        <div class="col-md-4 col-lg-4 icons" onmouseover="showGit()" onmouseout="hideGit()">
          <%= image_tag '/images/git.svg', width: 64%>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-4 col-lg-4 icons" onmouseover="showLaravel()" onmouseout="hideLaravel()">
          <%= image_tag '/images/laravel.svg', width: 64%>
        </div>
        <div class="col-md-4 col-lg-4 icons" onmouseover="showRspec()" onmouseout="hideRspec()">
          <%= image_tag '/images/rspec.svg', width: 64%>
        </div>
        <!-- 
        <div class="col-md-4 col-lg-4 icons" onmouseover="showGo()" onmouseout="hideGo()">
          <%= image_tag '/images/go.svg', width: 64%>
        </div>
        -->
      </div>
    </div>
    <div class="col-lg-5 desc">
      <div class="rails loren">
        Ruby on Rails é um framework livre que promete aumentar velocidade e 
        facilidade no desenvolvimento de sites orientados a banco de dados, 
        uma vez que é possível criar aplicações com base em estruturas pré-definidas.
      </div>
      <div class="graphql loren">
        GraphQL é uma linguagem de consulta criada pelo Facebook em 2012 e lançada 
        publicamente em 2015. É considerada uma alternativa para arquiteturas REST, 
        além de oferecer um serviço runtime para rodar comandos e consumir uma API.
      </div>
      <div class="heroku loren">
        Heroku é uma plataforma de nuvem como serviço que suporta 
        várias linguagens de programação. Uma das primeiras plataformas em 
        nuvem, o Heroku está em desenvolvimento desde junho de 2007, quando 
        suportava apenas a linguagem de programação Ruby, mas agora 
        suporta Java, Node.js, Scala, Clojure, Python, PHP e Go.
      </div>
      <div class="ruby loren">
        Ruby é uma linguagem de programação interpretada multiparadigma, 
        de tipagem dinâmica e forte, com gerenciamento de memória automático, 
        originalmente planejada e desenvolvida no Japão em 1995, 
        por Yukihiro "Matz" Matsumoto, para ser usada como linguagem de script.
      </div>
      <div class="postgresql loren">
        PostgreSQL é um sistema gerenciador de banco de dados objeto relacional, 
        desenvolvido como projeto de código aberto.
      </div>
      <div class="git loren">
        Git é um sistema de controle de versões distribuído, 
        usado principalmente no desenvolvimento de software, mas 
        pode ser usado para registrar o histórico de edições de qualquer tipo de arquivo.
      </div>
      <div class="laravel loren">
        Laravel é um framework PHP livre e open-source criado por 
        Taylor B. Otwell para o desenvolvimento de sistemas web que utilizam o padrão MVC.
      </div>
      <div class="rspec loren">
        RSpec é uma ferramenta de teste de linguagem específica
        do domínio do computador escrita na linguagem de 
        programação Ruby para testar o código Ruby.
        É uma estrutura de desenvolvimento orientada 
        por comportamento que é amplamente usada em aplicativos de produção.
      </div>
      
      <%# <div class="go">
        conubia semper adipiscing. augue nisi tellus malesuada ornare elementum vulputate<br>
        neque pharetra, nisl non ante hendrerit auctor hendrerit<br>
        turpis vivamus quis, facilisis neque primis
      </div> %>
    </div>
  </div>
</div>

<script type="text/javascript">
  
  let rails = document.querySelector(".rails")
  let graphql = document.querySelector(".graphql")
  let heroku = document.querySelector(".heroku")
  let ruby = document.querySelector(".ruby")
  let postgresql = document.querySelector(".postgresql")
  let git = document.querySelector(".git")
  let laravel = document.querySelector(".laravel")
  let rspec = document.querySelector(".rspec")
  // let go = document.querySelector(".go")

  // mostra a rails
  function showRails(){   
    rails.style.display = "block";
  }
  // esconde a rails
  function hideRails(){
    rails.style.display = "none"; 
  }
  function showGraphql(){   
    graphql.style.display = "block";
  }
  // esconde a graphql
  function hideGraphql(){
    graphql.style.display = "none"; 
  }
  function showHeroku(){   
    heroku.style.display = "block";
  }
  // esconde a heroku
  function hideHeroku(){
    heroku.style.display = "none"; 
  }
  function showRuby(){   
    ruby.style.display = "block";
  }
  // esconde a ruby
  function hideRuby(){
    ruby.style.display = "none"; 
  }
  function showPostgresql(){   
    postgresql.style.display = "block";
  }
  // esconde a postgresql
  function hidePostgresql(){
    postgresql.style.display = "none"; 
  }
  function showGit(){   
    git.style.display = "block";
  }
  // esconde a git
  function hideGit(){
    git.style.display = "none"; 
  }
  function showLaravel(){   
    laravel.style.display = "block";
  }
  // esconde a laravel
  function hideLaravel(){
    laravel.style.display = "none"; 
  }
  function showRspec(){   
    rspec.style.display = "block";
  }
  // esconde a rspec
  function hideRspec(){
    rspec.style.display = "none"; 
  }
  // function showGo(){   
  //   go.style.display = "block";
  // }
  // // esconde a go
  // function hideGo(){
  //   go.style.display = "none"; 
  // }
</script>

app/views/layouts/_footer.html.erb
<footer class="mt-auto">
  <div class="row justify-content-md-center">
    <a class="col-md-auto" href="https://www.instagram.com/luizdavi2/" toggle="_balnk">
      <%= image_tag '/images/instagram.png', width: 30%>
    </a>
      <a class="col-md-auto" href="https://www.linkedin.com/in/luizdmendes/">
      <%= image_tag '/images/linkedin.png', width: 30%>
    </a>
    <a class="col-md-auto" href="https://github.com/luiz-davi">
      <%= image_tag '/images/github.png', width: 30%>
    </a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to image_tag('/images/home.png', size: "40x40"), root_path,  class:"icon-home" %>
  <div class="row justify-content-md-center">
    <a class="col-4 col-md-2 link-header" data-turbolinks="false" href=<%= about_path %> >ABOUT</a>
    <a class="col-4 col-md-2 link-header" data-turbolinks="false" href=<%= skills_path %> >SKILLS</a>
    <a class="col-4 col-md-2 link-header" data-turbolinks="false" href=<%= projects_path %> >PROJECTS</a>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Luiz Davi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </head>

  <body class="body d-flex flex-column min-vh-100">

    <%= render 'layouts/header' %>

    <section class="main container">
      <%= yield %>
    </section>

    <%= render 'layouts/footer' %>

  </body>
</html>